---
all:
  children:
    controllers:
      hosts:
        brain:
          ansible_host: 192.168.1.23
          ansible_user: dar
          ansible_python_interpreter: /usr/bin/python3
    edge_nodes:
      hosts: {}
